server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /**
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
mybatis:
  type-aliases-package: org.seckill.entity
  mapperLocations: classpath:mapper/*.xml